send_request:
  args:
    request_json: ./request/MyCollection.postman_collection.json

dump:
  args:
    tables:
      - functions
      - roles
    out_path: ./output/

match_csv:
  args:
    expect_path: expect/
    actual_path: output/
    out_path: match_result/
